### ISSUE TITLE
ep-002 crashes on Android

### ISSUE THREAD

**Issue by iotashan** [appcelerator-developer-relations/Forging-Titanium#1]
I tried launching the example on Android using SDK 1.7.2, and it crashes. Here's the stacktrace:

> E/TitaniumModule(  409): (kroll$1: app://app.js) [1,1055] Error loading module named: NavigationController
> E/TitaniumModule(  409): java.lang.IllegalArgumentException: size < 0
> E/TitaniumModule(  409):  at java.io.ByteArrayOutputStream.<init>(ByteArrayOutputStream.java:65)
> E/TitaniumModule(  409):  at org.appcelerator.titanium.util.TiStreamHelper.toByteArray(TiStreamHelper.java:106)
> E/TitaniumModule(  409):  at org.appcelerator.titanium.TiBlob.getBytes(TiBlob.java:120)
> E/TitaniumModule(  409):  at org.appcelerator.titanium.TiBlob.getText(TiBlob.java:216)
> E/TitaniumModule(  409):  at ti.modules.titanium.TitaniumModule.require(TitaniumModule.java:431)
> E/TitaniumModule(  409):  at ti.modules.titanium.TitaniumModuleBindingGen$23.invoke(TitaniumModuleBindingGen.java:875)
> E/TitaniumModule(  409):  at org.appcelerator.kroll.KrollProxy$ThisMethod.invoke(KrollProxy.java:397)
> E/TitaniumModule(  409):  at org.appcelerator.kroll.KrollMethod.call(KrollMethod.java:51)
> E/TitaniumModule(  409):  at org.mozilla.javascript.Interpreter.interpretLoop(Interpreter.java:1701)
> E/TitaniumModule(  409):  at org.mozilla.javascript.Interpreter.interpret(Interpreter.java:854)
> E/TitaniumModule(  409):  at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:164)
> E/TitaniumModule(  409):  at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:426)
> E/TitaniumModule(  409):  at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3177)
> E/TitaniumModule(  409):  at org.mozilla.javascript.InterpretedFunction.exec(InterpretedFunction.java:175)
> E/TitaniumModule(  409):  at org.mozilla.javascript.Context.evaluateReader(Context.java:1142)
> E/TitaniumModule(  409):  at org.appcelerator.titanium.kroll.KrollContext$DefaultEvaluator.evaluateFile(KrollContext.java:105)
> E/TitaniumModule(  409):  at org.appcelerator.titanium.kroll.KrollContext.evaluateScript(KrollContext.java:306)
> E/TitaniumModule(  409):  at org.appcelerator.titanium.kroll.KrollContext.handleEvalFile(KrollContext.java:318)
> E/TitaniumModule(  409):  at org.appcelerator.titanium.kroll.KrollContext.handleMessage(KrollContext.java:217)
> E/TitaniumModule(  409):  at org.appcelerator.titanium.TiMessageQueue.handleMessage(TiMessageQueue.java:223)
> E/TitaniumModule(  409):  at android.os.Handler.dispatchMessage(Handler.java:95)
> E/TitaniumModule(  409):  at android.os.Looper.loop(Looper.java:130)
> E/TitaniumModule(  409):  at org.appcelerator.titanium.kroll.KrollHandlerThread.run(KrollHandlerThread.java:86)
> E/KrollMethod(  409): (kroll$1: app://app.js) [20,1075] Exception calling kroll method require, invocation: null ]
> E/KrollMethod(  409): org.mozilla.javascript.WrappedException: Wrapped java.lang.IllegalArgumentException: size < 0 (file:///android_asset/Resources/app.js#2)
> E/KrollMethod(  409):     at org.mozilla.javascript.Context.throwAsScriptRuntimeEx(Context.java:1786)
> E/KrollMethod(  409):     at ti.modules.titanium.TitaniumModule.require(TitaniumModule.java:453)
> E/KrollMethod(  409):     at ti.modules.titanium.TitaniumModuleBindingGen$23.invoke(TitaniumModuleBindingGen.java:875)
> E/KrollMethod(  409):     at org.appcelerator.kroll.KrollProxy$ThisMethod.invoke(KrollProxy.java:397)
> E/KrollMethod(  409):     at org.appcelerator.kroll.KrollMethod.call(KrollMethod.java:51)
> E/KrollMethod(  409):     at org.mozilla.javascript.Interpreter.interpretLoop(Interpreter.java:1701)
> E/KrollMethod(  409):     at script(file:///android_asset/Resources/app.js:2)
> E/KrollMethod(  409):     at org.mozilla.javascript.Interpreter.interpret(Interpreter.java:854)
> E/KrollMethod(  409):     at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:164)
> E/KrollMethod(  409):     at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:426)
> E/KrollMethod(  409):     at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3177)
> E/KrollMethod(  409):     at org.mozilla.javascript.InterpretedFunction.exec(InterpretedFunction.java:175)
> E/KrollMethod(  409):     at org.mozilla.javascript.Context.evaluateReader(Context.java:1142)
> E/KrollMethod(  409):     at org.appcelerator.titanium.kroll.KrollContext$DefaultEvaluator.evaluateFile(KrollContext.java:105)
> E/KrollMethod(  409):     at org.appcelerator.titanium.kroll.KrollContext.evaluateScript(KrollContext.java:306)
> E/KrollMethod(  409):     at org.appcelerator.titanium.kroll.KrollContext.handleEvalFile(KrollContext.java:318)
> E/KrollMethod(  409):     at org.appcelerator.titanium.kroll.KrollContext.handleMessage(KrollContext.java:217)
> E/KrollMethod(  409):     at org.appcelerator.titanium.TiMessageQueue.handleMessage(TiMessageQueue.java:223)
> E/KrollMethod(  409):     at android.os.Handler.dispatchMessage(Handler.java:95)
> E/KrollMethod(  409):     at android.os.Looper.loop(Looper.java:130)
> E/KrollMethod(  409):     at org.appcelerator.titanium.kroll.KrollHandlerThread.run(KrollHandlerThread.java:86)
> E/KrollMethod(  409): Caused by: java.lang.IllegalArgumentException: size < 0
> E/KrollMethod(  409):     at java.io.ByteArrayOutputStream.<init>(ByteArrayOutputStream.java:65)
> E/KrollMethod(  409):     at org.appcelerator.titanium.util.TiStreamHelper.toByteArray(TiStreamHelper.java:106)
> E/KrollMethod(  409):     at org.appcelerator.titanium.TiBlob.getBytes(TiBlob.java:120)
> E/KrollMethod(  409):     at org.appcelerator.titanium.TiBlob.getText(TiBlob.java:216)
> E/KrollMethod(  409):     at ti.modules.titanium.TitaniumModule.require(TitaniumModule.java:431)
> E/KrollMethod(  409):     ... 18 more
> E/KrollContext(  409): (kroll$1: app://app.js) [11,1086] Error evaluating source: Wrapped java.lang.IllegalArgumentException: size < 0 (file:///android_asset/Resources/app.js#2)
> E/KrollContext(  409): org.mozilla.javascript.WrappedException: Wrapped java.lang.IllegalArgumentException: size < 0 (file:///android_asset/Resources/app.js#2)
> E/KrollContext(  409):    at org.mozilla.javascript.Context.throwAsScriptRuntimeEx(Context.java:1786)
> E/KrollContext(  409):    at ti.modules.titanium.TitaniumModule.require(TitaniumModule.java:453)
> E/KrollContext(  409):    at ti.modules.titanium.TitaniumModuleBindingGen$23.invoke(TitaniumModuleBindingGen.java:875)
> E/KrollContext(  409):    at org.appcelerator.kroll.KrollProxy$ThisMethod.invoke(KrollProxy.java:397)
> E/KrollContext(  409):    at org.appcelerator.kroll.KrollMethod.call(KrollMethod.java:51)
> E/KrollContext(  409):    at org.mozilla.javascript.Interpreter.interpretLoop(Interpreter.java:1701)
> E/KrollContext(  409):    at script(file:///android_asset/Resources/app.js:2)
> E/KrollContext(  409):    at org.mozilla.javascript.Interpreter.interpret(Interpreter.java:854)
> E/KrollContext(  409):    at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:164)
> E/KrollContext(  409):    at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:426)
> E/KrollContext(  409):    at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3177)
> E/KrollContext(  409):    at org.mozilla.javascript.InterpretedFunction.exec(InterpretedFunction.java:175)
> E/KrollContext(  409):    at org.mozilla.javascript.Context.evaluateReader(Context.java:1142)
> E/KrollContext(  409):    at org.appcelerator.titanium.kroll.KrollContext$DefaultEvaluator.evaluateFile(KrollContext.java:105)
> E/KrollContext(  409):    at org.appcelerator.titanium.kroll.KrollContext.evaluateScript(KrollContext.java:306)
> E/KrollContext(  409):    at org.appcelerator.titanium.kroll.KrollContext.handleEvalFile(KrollContext.java:318)
> E/KrollContext(  409):    at org.appcelerator.titanium.kroll.KrollContext.handleMessage(KrollContext.java:217)
> E/KrollContext(  409):    at org.appcelerator.titanium.TiMessageQueue.handleMessage(TiMessageQueue.java:223)
> E/KrollContext(  409):    at android.os.Handler.dispatchMessage(Handler.java:95)
> E/KrollContext(  409):    at android.os.Looper.loop(Looper.java:130)
> E/KrollContext(  409):    at org.appcelerator.titanium.kroll.KrollHandlerThread.run(KrollHandlerThread.java:86)
> E/KrollContext(  409): Caused by: java.lang.IllegalArgumentException: size < 0
> E/KrollContext(  409):    at java.io.ByteArrayOutputStream.<init>(ByteArrayOutputStream.java:65)
> E/KrollContext(  409):    at org.appcelerator.titanium.util.TiStreamHelper.toByteArray(TiStreamHelper.java:106)
> E/KrollContext(  409):    at org.appcelerator.titanium.TiBlob.getBytes(TiBlob.java:120)
> E/KrollContext(  409):    at org.appcelerator.titanium.TiBlob.getText(TiBlob.java:216)
> E/KrollContext(  409):    at ti.modules.titanium.TitaniumModule.require(TitaniumModule.java:431)
> E/KrollContext(  409):    ... 18 more
> E/TiJSError(  409): (kroll$1: app://app.js) [8,1094] ----- Titanium Javascript Runtime Error -----
> E/TiJSError(  409): (kroll$1: app://app.js) [1,1095] - In file:///android_asset/Resources/app.js:2,0
> E/TiJSError(  409): (kroll$1: app://app.js) [1,1096] - Message: Wrapped java.lang.IllegalArgumentException: size < 0 (file:///android_asset/Resources/app.js#2)
> E/TiJSError(  409): (kroll$1: app://app.js) [1,1097] - Source: null

**Comment by iotashan** [comment]
Fixed in my pull request
